# Generated by Django 5.1.6 on 2025-03-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='region',
            field=models.CharField(default='East', max_length=100),
            preserve_default=False,
        ),
    ]
